language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "xJ91yt2a0yf8UXoJR1YnIlqhsh+e9gl/OmrxBclSi+87mYZlE9x8eUhwVU4P9u3rdllK4B8nGz7EUvw919DnWAlsO6t7PJDWXksv68YyV/bbm4i6FkAJ4Jl1KLIDRG1lbMigG4ZIclUTMyUyJsQI0DXzvXWS3Kmn2TuEAQw0rothrgOjrMFx+HTnbzkxQzFKIGTU9ce/PaE7Rh+Ycbhxv2u7jVruPHtnMwefWUXOkAVu00E/ApYs+RkpWpZyUiMootCP++Y+MDTLTQbRoevS5c8Qv5Ak8469mo+Cflzok9czkDGvz/71eMJIdSH82X79IqWghTuh8GgVRglHKcGS/7ZatQH3dkvuI2E38bKUKFpS1I+dbWNFfvSE6y6IHz3Y/lJ+XROT/a2q3gqavLsimfqQCXA5pjfLq2yB51HK6IlinUjWS76ua4sDpImZPpM2tGySAN6B2OMFC5kULjJS3GZTco8TpyLs5e2AbFCT0NJHgBxohztXvl66Xn3frsG3FZGGwdUlEzdajFREavP3nVv8ifN1HcitRmLvvsH7xLBKPzNOhE4t5/K84huIN9l500G8f4e+hP8r3V+pFN+ME5rnQoaiSzoGOCf75/oEhnCWPkVs41XnR7S3WtZ8IuFmxlYU5lrz2cwqStKVSW/7ETMlQpRweL8fB13BxmNnQ/E="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "2NTX5wE8Ix+J331SLa5cO7yrgn2VbTseEawYRRWyWB3h1Mun3diWwIz7iPVqqcgpYZW3aA1YPhHxDRs43mdx/txch4xCgZW5Id028CCuChwZ091EbQDQrt4fKPrIBQ/iHE20Eu047e6LDS6irUqIGq7NzMAMUU5/n+fxLOu38ge8gkhuhJJgyHl8VDTrXKBD4KswjDkGk5aInjq6VSpghbcZizWfe2Rp//hAKb1GJcVTOqPvMRqSpli3a7931/4l3efAFJYAjlxku3vcFqaZzEp484NjnZKl6mDfHTVYZlmi8sd5FDmW8WUpapN9pPsY2wYAwXJg3RpLtRLv6W2zbnxGRLJbIxDZDDXU9cDtEZg03hH3lFXWQmLHbgXgo+B9lg3UkjwTUQWwzCNXHvQs+wyfHMUr9lBHA85tRR+8OqvnNXseAY8of8OXuMOlhSeKMhCjzzTAOW6nq8UmMia5nIlgbj8E1iAsgO5kHo2RI8tvOW6YTIOfTiESQ7NWg2NRJE/ozDM1iE/+Ay+hZKGxJg68/xtPmigtTFn/rAIqU3V7QVKouHzuMlX5rx5s6TQc+OZlX1+k1fjfBGfgCYlBo2yOauFz9Nw8zyT5DUNeTenNTPWX/Gu+DDnl3i+hczvUYojCgQnGIni8ze+6M3X64eApTlom+a2m5XOGtmpkgq8="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "2faUqKbKCOFlUqCpOTV12QSs7D9hOCK8T/ZTVMd/QNvkwHjrESOYSRGpHbRJXMbffLTg0bKF4onfuz9yHYB6QR7G36umNCjd9RvV8Ta229LwGKC2uUcuhaoHROzVcmYg+6bVjYoBVfz2io5cR3tILyeF6X5SpVIAq9lHxtb+xapkz6WfQk0pX2rAj1Zzx2yLqdOqtULUdgmRjtG3etBRXJOLr4b/+MIGIDNdz/OTXwSWRAdKD3Zj96WnQ9coJkC2EOpTmLssIo3xxYbvWbwH662VOuZZVjp8f3/1yXw3Zji1M3ANwBWaUxq0k685GQ35ZGkhIhaSJ8qeuyhAWQSOPxqjHH2myLK0DJ8FnoFPUZbtyQxMrpzpvAF2YwxX4WvOg7qJ5YXFf3jpICqKsj3B8ziH9ACD18CO6IVKth8aGW9Txcbo6oI7QnyIMs6dltrQl0jvTS6H4gKBMq2m6wjCIg5z2HTTy/MFBWUDYBgXmTGydVEG+vvor8u9LAHQnZWxu8jupq6T552NHKYhXl2NnZOtopbQM3513OwpYXmdInHafpZQWiblLiGVgtsX+gVz+azMCAl3dAzdlAQ/X2dwGRl8g+m+eqWdldBih7EWcSHKnDkhtuibzsPBujxMtTLL5VELkQH1+A6wdVhyotUPZpsia8c+C+9UvW/u93+Ap6U="
    - # ^^ GPG_KEY_NAME
    - secure: "Ww67aD1ltIRdgnkRonWltuJu+5fugTMVEjnvFS742OoybqXDixky8UyWMfQd8JysEYumrOzGGX5+Ts3F6g5xjSG+Dv1UBmPAB6I2WxhWX1wCPuqnowZKe6CkdhN6Oi+xElJ1ziET7OzwSYGWo9e6dd8R1rJQZ/4+sDao6JF4/h8cPAU0qk91netRYifvyoz5CwUpsZo6maE6HMUSO+SIQ2jacey9sNDRaBS/19n5fOo5I/K3BfKq61dKaiCLnxGEOqjdGDGwfHOHc/8h7v+IWS6DYFh0uipJ5fZrzg/VobR3Sy2GLfBE28ThbS6uRxNVOnC8xWL1gQ9wP2B0m+UE/UrAU6qk7kgTxCGaFjM83LqMp/nQU7lL+hNJzPYDBPNLaxOF+WC8DdS4JSCcbfEbs+DMgS5V7N8Nz1ZdhgzG2Rw4I636znt8EFoaY4Pbo2m+1xcX5Tp9XQ5e+vKAAYAiET6u1cWXkaxy2Fi/C7HexlROi6iZn+Ojaa8og/VuIZAxREYb/fEEBfqnImDfqs/HLEuhutMUZuWpZkrUnHlMqqleY1PTcKTmo8LjhlsSSfX8hsGRaOxmeP1ysgy3jvBJ+Ju8rLcVJpqnNKEF8o2FsU2QEyP4RZGiOaiTgSiyJ7RBx2YLv5hM+O58BN/XfXDcCdK8ENW75w0vv2CV01TMYZg="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

before_install:
  - ./mvnw install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - netstat -plant
  - lsof
  - ./mvnw -B -P !build-extras test

deploy:
  sudo: false
  services: []
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
